// auto-generated (see utils/README.md)
package cmw

var mt2cf = map[string]uint16{
	`application/cbor`:                         60,
	`application/multipart-core`:               62,
	`application/edhoc+cbor-seq`:               64,
	`application/senml+json`:                   110,
	`application/vnd.ocf+cbor`:                 10000,
	`application/exi`:                          47,
	`application/merge-patch+json`:             52,
	`application/cose; cose-type="cose-mac"`:   97,
	`application/yang-data+cbor; id=sid`:       140,
	`application/coap-eap`:                     269,
	`application/sensml+xml`:                   311,
	`application/eat+cwt`:                      263,
	`application/ce+cbor`:                      10571,
	`image/png`:                                23,
	`application/concise-problem-details+cbor`: 257,
	`application/yang-sid+json`:                260,
	`application/eat-bun+json`:                 266,
	`application/eat+cwt; eat_profile="tag:psacertified.org,2019:psa#legacy"`: 10004,
	`application/javascript`:                  10002,
	`image/svg+xml`:                           30000,
	`application/cose; cose-type="cose-sign"`: 98,
	`application/sensml+json`:                 111,
	`application/pkixcmp`:                     259,
	`application/eat-ucs+json`:                268,
	`application/yang-data+cbor`:              340,
	`application/oscore`:                      10001,
	`application/json`:                        50,
	`application/uccs+cbor`:                   601,
	`application/eat+cwt; eat_profile="tag:psacertified.org,2023:psa#tfm"`: 10003,
	`application/toc+cbor`:                                      10570,
	`application/vnd.oma.lwm2m+json`:                            11543,
	`application/cose; cose-type="cose-encrypt0"`:               16,
	`application/cbor-seq`:                                      63,
	`application/senml-etch+cbor`:                               322,
	`application/yang-data+cbor; id=name`:                       341,
	`application/cwt`:                                           61,
	`application/cose; cose-type="cose-encrypt"`:                96,
	`application/vnd.oma.lwm2m+cbor`:                            11544,
	`application/csrattrs`:                                      285,
	`application/pkix-cert`:                                     287,
	`application/cose; cose-type="cose-mac0"`:                   17,
	`application/octet-stream`:                                  42,
	`application/cid-edhoc+cbor-seq`:                            65,
	`application/senml+cbor`:                                    112,
	`application/swid+cbor`:                                     258,
	`application/eat-bun+cbor`:                                  265,
	`text/plain; charset=utf-8`:                                 0,
	`image/jpeg`:                                                22,
	`application/aif+json`:                                      291,
	`application/eat+cwt; eat_profile=2.16.840.1.113741.1.16.1`: 10005,
	`application/xml`:                                           41,
	`application/sensml+cbor`:                                   113,
	`application/sensml-exi`:                                    115,
	`application/eat+jwt`:                                       264,
	`application/dots+cbor`:                                     271,
	`application/pkcs10`:                                        286,
	`application/ace+cbor`:                                      19,
	`application/cose-key-set`:                                  102,
	`application/senml-etch+json`:                               320,
	`application/json-patch+json`:                               51,
	`application/missing-blocks+cbor-seq`:                       272,
	`application/tm+json`:                                       433,
	`application/td+json`:                                       432,
	`application/cose; cose-type="cose-sign1"`:                  18,
	`image/gif`:                                                 21,
	`application/coap-group+json`:                               256,
	`application/pkcs8`:                                         284,
	`application/aif+cbor`:                                      290,
	`application/senml+xml`:                                     310,
	`text/css`:                                                  20000,
	`application/link-format`:                                   40,
	`application/ace-groupcomm+cbor`:                            261,
	`application/eat-ucs+cbor`:                                  267,
	`application/pkcs7-mime; smime-type=server-generated-key`:   280,
	`application/pkcs7-mime; smime-type=certs-only`:             281,
	`application/vnd.oma.lwm2m+tlv`:                             11542,
	`application/cose-key`:                                      101,
	`application/senml-exi`:                                     114,
	`application/ace-trl+cbor`:                                  262,
}

var cf2mt = map[uint16]string{
	0:     `text/plain; charset=utf-8`,
	22:    `image/jpeg`,
	291:   `application/aif+json`,
	41:    `application/xml`,
	113:   `application/sensml+cbor`,
	115:   `application/sensml-exi`,
	264:   `application/eat+jwt`,
	271:   `application/dots+cbor`,
	286:   `application/pkcs10`,
	10005: `application/eat+cwt; eat_profile=2.16.840.1.113741.1.16.1`,
	19:    `application/ace+cbor`,
	102:   `application/cose-key-set`,
	320:   `application/senml-etch+json`,
	51:    `application/json-patch+json`,
	272:   `application/missing-blocks+cbor-seq`,
	433:   `application/tm+json`,
	18:    `application/cose; cose-type="cose-sign1"`,
	21:    `image/gif`,
	256:   `application/coap-group+json`,
	284:   `application/pkcs8`,
	290:   `application/aif+cbor`,
	310:   `application/senml+xml`,
	432:   `application/td+json`,
	40:    `application/link-format`,
	261:   `application/ace-groupcomm+cbor`,
	267:   `application/eat-ucs+cbor`,
	280:   `application/pkcs7-mime; smime-type=server-generated-key`,
	281:   `application/pkcs7-mime; smime-type=certs-only`,
	11542: `application/vnd.oma.lwm2m+tlv`,
	20000: `text/css`,
	101:   `application/cose-key`,
	114:   `application/senml-exi`,
	262:   `application/ace-trl+cbor`,
	60:    `application/cbor`,
	62:    `application/multipart-core`,
	64:    `application/edhoc+cbor-seq`,
	110:   `application/senml+json`,
	10000: `application/vnd.ocf+cbor`,
	47:    `application/exi`,
	52:    `application/merge-patch+json`,
	97:    `application/cose; cose-type="cose-mac"`,
	140:   `application/yang-data+cbor; id=sid`,
	269:   `application/coap-eap`,
	311:   `application/sensml+xml`,
	263:   `application/eat+cwt`,
	10571: `application/ce+cbor`,
	23:    `image/png`,
	257:   `application/concise-problem-details+cbor`,
	260:   `application/yang-sid+json`,
	266:   `application/eat-bun+json`,
	10004: `application/eat+cwt; eat_profile="tag:psacertified.org,2019:psa#legacy"`,
	30000: `image/svg+xml`,
	98:    `application/cose; cose-type="cose-sign"`,
	111:   `application/sensml+json`,
	259:   `application/pkixcmp`,
	268:   `application/eat-ucs+json`,
	340:   `application/yang-data+cbor`,
	10001: `application/oscore`,
	10002: `application/javascript`,
	50:    `application/json`,
	601:   `application/uccs+cbor`,
	10003: `application/eat+cwt; eat_profile="tag:psacertified.org,2023:psa#tfm"`,
	10570: `application/toc+cbor`,
	11543: `application/vnd.oma.lwm2m+json`,
	16:    `application/cose; cose-type="cose-encrypt0"`,
	63:    `application/cbor-seq`,
	322:   `application/senml-etch+cbor`,
	341:   `application/yang-data+cbor; id=name`,
	61:    `application/cwt`,
	96:    `application/cose; cose-type="cose-encrypt"`,
	11544: `application/vnd.oma.lwm2m+cbor`,
	287:   `application/pkix-cert`,
	17:    `application/cose; cose-type="cose-mac0"`,
	42:    `application/octet-stream`,
	65:    `application/cid-edhoc+cbor-seq`,
	112:   `application/senml+cbor`,
	258:   `application/swid+cbor`,
	265:   `application/eat-bun+cbor`,
	285:   `application/csrattrs`,
}
