// auto-generated (see utils/README.md)
package cmw

var mt2cf = map[string]uint16{
	`application/cose; cose-type="cose-mac0"`:                 17,
	`application/cid-edhoc+cbor-seq`:                          65,
	`application/senml+cbor`:                                  112,
	`application/aif+json`:                                    291,
	`application/xml`:                                         41,
	`application/cose-key`:                                    101,
	`application/cose; cose-type="cose-sign1"`:                18,
	`application/pkcs7-mime; smime-type=server-generated-key`: 280,
	`application/concise-problem-details+cbor`:                257,
	`application/toc+cbor`:                                    10570,
	`application/multipart-core`:                              62,
	`application/cose-key-set`:                                102,
	`application/sensml+json`:                                 111,
	`application/senml-etch+cbor`:                             322,
	`text/css`:                                                20000,
	`image/gif`:                                               21,
	`application/octet-stream`:                                42,
	`application/cwt`:                                         61,
	`application/sensml+cbor`:                                 113,
	`application/senml-exi`:                                   114,
	`application/coap-group+json`:                             256,
	`application/yang-sid+json`:                               260,
	`application/senml-etch+json`:                             320,
	`application/javascript`:                                  10002,
	`application/senml+xml`:                                   310,
	`application/vnd.oma.lwm2m+tlv`:                           11542,
	`application/cose; cose-type="cose-mac"`:                  97,
	`application/yang-data+cbor; id=sid`:                      140,
	`application/ace-trl+cbor`:                                262,
	`application/dots+cbor`:                                   271,
	`application/sensml+xml`:                                  311,
	`application/ce+cbor`:                                     10571,
	`application/vnd.oma.lwm2m+json`:                          11543,
	`application/link-format`:                                 40,
	`application/cbor`:                                        60,
	`application/aif+cbor`:                                    290,
	`application/yang-data+cbor`:                              340,
	`application/tm+json`:                                     433,
	`application/cose; cose-type="cose-encrypt0"`:             16,
	`image/jpeg`:                                              22,
	`application/merge-patch+json`:                            52,
	`application/cose; cose-type="cose-sign"`:                 98,
	`application/ace-groupcomm+cbor`:                          261,
	`application/pkcs8`:                                       284,
	`application/pkcs10`:                                      286,
	`application/yang-data+cbor; id=name`:                     341,
	`application/oscore`:                                      10001,
	`application/cbor-seq`:                                    63,
	`application/senml+json`:                                  110,
	`image/svg+xml`:                                           30000,
	`application/sensml-exi`:                                  115,
	`application/vnd.ocf+cbor`:                                10000,
	`text/plain; charset=utf-8`:                               0,
	`application/pkcs7-mime; smime-type=certs-only`:           281,
	`application/pkix-cert`:                                   287,
	`application/json-patch+json`:                             51,
	`application/edhoc+cbor-seq`:                              64,
	`application/cose; cose-type="cose-encrypt"`:              96,
	`application/swid+cbor`:                                   258,
	`application/csrattrs`:                                    285,
	`application/json`:                                        50,
	`application/missing-blocks+cbor-seq`:                     272,
	`application/vnd.oma.lwm2m+cbor`:                          11544,
	`application/ace+cbor`:                                    19,
	`image/png`:                                               23,
	`application/exi`:                                         47,
	`application/pkixcmp`:                                     259,
	`application/td+json`:                                     432,
}

var cf2mt = map[uint16]string{
	50:    `application/json`,
	272:   `application/missing-blocks+cbor-seq`,
	11544: `application/vnd.oma.lwm2m+cbor`,
	19:    `application/ace+cbor`,
	23:    `image/png`,
	47:    `application/exi`,
	259:   `application/pkixcmp`,
	432:   `application/td+json`,
	17:    `application/cose; cose-type="cose-mac0"`,
	65:    `application/cid-edhoc+cbor-seq`,
	112:   `application/senml+cbor`,
	291:   `application/aif+json`,
	41:    `application/xml`,
	101:   `application/cose-key`,
	18:    `application/cose; cose-type="cose-sign1"`,
	280:   `application/pkcs7-mime; smime-type=server-generated-key`,
	257:   `application/concise-problem-details+cbor`,
	10570: `application/toc+cbor`,
	62:    `application/multipart-core`,
	102:   `application/cose-key-set`,
	111:   `application/sensml+json`,
	322:   `application/senml-etch+cbor`,
	20000: `text/css`,
	320:   `application/senml-etch+json`,
	21:    `image/gif`,
	42:    `application/octet-stream`,
	61:    `application/cwt`,
	113:   `application/sensml+cbor`,
	114:   `application/senml-exi`,
	256:   `application/coap-group+json`,
	260:   `application/yang-sid+json`,
	10002: `application/javascript`,
	310:   `application/senml+xml`,
	11542: `application/vnd.oma.lwm2m+tlv`,
	97:    `application/cose; cose-type="cose-mac"`,
	140:   `application/yang-data+cbor; id=sid`,
	262:   `application/ace-trl+cbor`,
	271:   `application/dots+cbor`,
	311:   `application/sensml+xml`,
	10571: `application/ce+cbor`,
	11543: `application/vnd.oma.lwm2m+json`,
	40:    `application/link-format`,
	60:    `application/cbor`,
	290:   `application/aif+cbor`,
	340:   `application/yang-data+cbor`,
	433:   `application/tm+json`,
	341:   `application/yang-data+cbor; id=name`,
	16:    `application/cose; cose-type="cose-encrypt0"`,
	22:    `image/jpeg`,
	52:    `application/merge-patch+json`,
	98:    `application/cose; cose-type="cose-sign"`,
	261:   `application/ace-groupcomm+cbor`,
	284:   `application/pkcs8`,
	286:   `application/pkcs10`,
	10001: `application/oscore`,
	63:    `application/cbor-seq`,
	110:   `application/senml+json`,
	30000: `image/svg+xml`,
	115:   `application/sensml-exi`,
	10000: `application/vnd.ocf+cbor`,
	0:     `text/plain; charset=utf-8`,
	281:   `application/pkcs7-mime; smime-type=certs-only`,
	287:   `application/pkix-cert`,
	51:    `application/json-patch+json`,
	64:    `application/edhoc+cbor-seq`,
	96:    `application/cose; cose-type="cose-encrypt"`,
	258:   `application/swid+cbor`,
	285:   `application/csrattrs`,
}
