// auto-generated (see utils/README.md)
package cmw

var mt2cf = map[string]uint16{
	`application/cbor`:                              11060,
	`image/png`:                                     23,
	`application/multipart-core`:                    62,
	`application/cose-key-set`:                      102,
	`application/sensml+cbor`:                       113,
	`application/aif+cbor`:                          290,
	`application/yang-data+cbor`:                    340,
	`application/pkcs7-mime; smime-type=certs-only`: 281,
	`application/pkcs10`:                            286,
	`application/td+json`:                           432,
	`application/json`:                              11050,
	`application/dots+cbor`:                         271,
	`application/pkcs7-mime; smime-type=server-generated-key`: 280,
	`application/pkcs8`:                           284,
	`application/pkix-cert`:                       287,
	`application/link-format`:                     40,
	`application/aif+json`:                        291,
	`application/vnd.ocf+cbor`:                    10000,
	`text/plain; charset=utf-8`:                   0,
	`application/senml+xml`:                       310,
	`application/cose; cose-type="cose-sign1"`:    18,
	`application/json-patch+json`:                 51,
	`application/tm+json`:                         433,
	`application/octet-stream`:                    42,
	`application/merge-patch+json`:                52,
	`application/sensml+xml`:                      311,
	`application/vnd.oma.lwm2m+cbor`:              11544,
	`application/cose; cose-type="cose-encrypt0"`: 16,
	`application/exi`:                             47,
	`application/cose; cose-type="cose-encrypt"`:  96,
	`application/coap-group+json`:                 256,
	`application/cose; cose-type="cose-sign"`:     98,
	`application/cose-key`:                        101,
	`application/senml+cbor`:                      112,
	`application/senml-etch+json`:                 320,
	`image/jpeg`:                                  22,
	`application/sensml+json`:                     111,
	`application/vnd.oma.lwm2m+tlv`:               11542,
	`application/cose; cose-type="cose-mac0"`:     17,
	`application/ace+cbor`:                        19,
	`application/senml-exi`:                       114,
	`application/swid+cbor`:                       258,
	`application/missing-blocks+cbor-seq`:         272,
	`application/senml-etch+cbor`:                 322,
	`application/cbor-seq`:                        63,
	`application/senml+json`:                      110,
	`application/javascript`:                      10002,
	`image/svg+xml`:                               30000,
	`text/css`:                                    20000,
	`application/xml`:                             41,
	`application/cose; cose-type="cose-mac"`:      97,
	`application/sensml-exi`:                      115,
	`application/yang-data+cbor; id=sid`:          140,
	`application/csrattrs`:                        285,
	`application/vnd.oma.lwm2m+json`:              11543,
	`image/gif`:                                   21,
	`application/cwt`:                             61,
	`application/concise-problem-details+cbor`:    257,
	`application/yang-data+cbor; id=name`:         341,
	`application/oscore`:                          10001,
}

var cf2mt = map[uint16]string{
	11060: `application/cbor`,
	23:    `image/png`,
	62:    `application/multipart-core`,
	102:   `application/cose-key-set`,
	113:   `application/sensml+cbor`,
	290:   `application/aif+cbor`,
	340:   `application/yang-data+cbor`,
	281:   `application/pkcs7-mime; smime-type=certs-only`,
	286:   `application/pkcs10`,
	432:   `application/td+json`,
	284:   `application/pkcs8`,
	287:   `application/pkix-cert`,
	11050: `application/json`,
	271:   `application/dots+cbor`,
	280:   `application/pkcs7-mime; smime-type=server-generated-key`,
	40:    `application/link-format`,
	291:   `application/aif+json`,
	10000: `application/vnd.ocf+cbor`,
	0:     `text/plain; charset=utf-8`,
	310:   `application/senml+xml`,
	18:    `application/cose; cose-type="cose-sign1"`,
	51:    `application/json-patch+json`,
	433:   `application/tm+json`,
	11544: `application/vnd.oma.lwm2m+cbor`,
	42:    `application/octet-stream`,
	52:    `application/merge-patch+json`,
	311:   `application/sensml+xml`,
	256:   `application/coap-group+json`,
	16:    `application/cose; cose-type="cose-encrypt0"`,
	47:    `application/exi`,
	96:    `application/cose; cose-type="cose-encrypt"`,
	320:   `application/senml-etch+json`,
	98:    `application/cose; cose-type="cose-sign"`,
	101:   `application/cose-key`,
	112:   `application/senml+cbor`,
	22:    `image/jpeg`,
	111:   `application/sensml+json`,
	258:   `application/swid+cbor`,
	272:   `application/missing-blocks+cbor-seq`,
	322:   `application/senml-etch+cbor`,
	11542: `application/vnd.oma.lwm2m+tlv`,
	17:    `application/cose; cose-type="cose-mac0"`,
	19:    `application/ace+cbor`,
	114:   `application/senml-exi`,
	30000: `image/svg+xml`,
	63:    `application/cbor-seq`,
	110:   `application/senml+json`,
	10002: `application/javascript`,
	140:   `application/yang-data+cbor; id=sid`,
	285:   `application/csrattrs`,
	11543: `application/vnd.oma.lwm2m+json`,
	20000: `text/css`,
	41:    `application/xml`,
	97:    `application/cose; cose-type="cose-mac"`,
	115:   `application/sensml-exi`,
	341:   `application/yang-data+cbor; id=name`,
	10001: `application/oscore`,
	21:    `image/gif`,
	61:    `application/cwt`,
	257:   `application/concise-problem-details+cbor`,
}
