name: cover ≥84%
on: [push, pull_request]
jobs:
  cover:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: "1.19"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Go Coverage
      run: |
        go version
        go test -short -cover | grep -o "coverage:.*of statements$" | python scripts/cov.py
      shell: bash
